# Site Settings
paginate: 6
paginate_path: "/page:num"

title: 파이의 개발 블로그
subtitle: Pi(3.14)'s Development Blog
description: 게으르고 싶지 않은 파이의 개발 블로그

baseurl: ""
url: "https://ghdwlgns.github.io"

cover: "/img/home.jpg"
